name: CI

on:
#   push:
#     branches:
#       - dev
  workflow_dispatch:

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v2
      
    #   - name: Docker Compose
    #     uses: hoverkraft-tech/compose-action@v2.0.1
    #     with:
    #         compose-file: ./docker-compose.yml
      
    #   - name: Unit Test
    #     run: |
    #         docker pull busybox:latest
    #         docker exec codynflux bash -c "cd /app && pytest -s"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build the image
        run: |
          docker build --pull --no-cache -f dockerfile -t ${{ secrets.DOCKER_USERNAME }}/codynflux:dev .